### ISSUE TITLE
TCP Provider: Error code 0x2746

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/db-extractor-mssql#109]
```
[2019-03-18 20:00:42] CRITICAL: PDOException:SQLSTATE[08S01]: [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2746 

{
    "errFile": "/code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Extractor/Extractor.php",
    "errLine": 289,
    "errCode": "08S01",
    "errTrace": "#0 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Extractor/Extractor.php(289): PDOStatement->fetch(2)\n#1 /code/src/Keboola/DbExtractor/Extractor/MSSQL.php(255): Keboola\\DbExtractor\\Extractor\\Extractor->writeToCsv(Object(PDOStatement), Object(Keboola\\Csv\\CsvFile), true)\n#2 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(166): Keboola\\DbExtractor\\Extractor\\MSSQL->export(Array)\n#3 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(65): Keboola\\DbExtractor\\Application->runAction()\n#4 /code/src/run.php(55): Keboola\\DbExtractor\\Application->run()\n#5 {main}",
    "errPrevious": ""
}

#0 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Extractor/Extractor.php(289): PDOStatement->fetch(2)
#1 /code/src/Keboola/DbExtractor/Extractor/MSSQL.php(255): Keboola\\DbExtractor\\Extractor\\Extractor->writeToCsv(Object(PDOStatement), Object(Keboola\\Csv\\CsvFile), true)
#2 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(166): Keboola\\DbExtractor\\Extractor\\MSSQL->export(Array)
#3 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(65): Keboola\\DbExtractor\\Application->runAction()
#4 /code/src/run.php(55): Keboola\\DbExtractor\\Application->run()
#5 {main}

```

maybe a retry will suffice?

**Comment by pivnicek** [comment]
Yes, all queries should be individually wrapped in the retry proxy.
