### ISSUE TITLE
Session Provider: Connection has been closed by peer [xFFFFFFFF].

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/db-extractor-mssql#111]
další kandidát na retry

```
(2) [2019-03-20 15:35:00] CRITICAL: PDOException:SQLSTATE[08S01]: 
[Microsoft][ODBC Driver 17 for SQL Server]Session Provider: 
Connection has been closed by peer [xFFFFFFFF].  
```

```
#0 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Extractor/Extractor.php(289): PDOStatement->fetch(2)
#1 /code/src/Keboola/DbExtractor/Extractor/MSSQL.php(255): Keboola\DbExtractor\Extractor\Extractor->writeToCsv(Object(PDOStatement), Object(Keboola\Csv\CsvFile), true)
#2 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(170): Keboola\DbExtractor\Extractor\MSSQL->export(Array)
#3 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(65): Keboola\DbExtractor\Application->runAction()
#4 /code/src/run.php(55): Keboola\DbExtractor\Application->run()
#5 {main}
```

**Comment by ondrejhlavacek** [comment]
duplicate of #49
