### ISSUE TITLE
Undefined index schema

### ISSUE THREAD

**Issue by odinuv** [keboola/db-extractor-mssql#43]
[2018-08-31 10:38:56] CRITICAL: ErrorException:Undefined index: schema {"errFile":"/code/src/Keboola/DbExtractor/Extractor/MSSQL.php","errLine":73,"errCode":0,"errTrace":"#0 /code/src/Keboola/DbExtractor/Extractor/MSSQL.php(73): Keboola\\DbExtractor\\Application::Keboola\\DbExtractor\\{closure}(8, 'Undefined index...', '/code/src/Keboo...', 73, Array)\n#1 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(159): Keboola\\DbExtractor\\Extractor\\MSSQL->export(Array)\n#2 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(60): Keboola\\DbExtractor\\Application->runAction()\n#3 /code/src/run.php(55): Keboola\\DbExtractor\\Application->run()\n#4 {main}","errPrevious":""} []

**Comment by odinuv** [comment]
should be $table['table']['schema'] cause it gets:

```
array(8) {
  ["enabled"]=>
  bool(true)
  ["name"]=>
  string(5) "SALDO"
  ["incremental"]=>
  bool(false)
  ["outputTable"]=>
  string(40) "in.c-keboola-ex-db-mssql-392932482.saldo"
  ["table"]=>
  array(2) {
    ["schema"]=>
    string(3) "dbo"
    ["tableName"]=>
    string(5) "SALDO"
  }
  ["columns"]=>
  array(0) {
  }
  ["primaryKey"]=>
  array(1) {
    [0]=>
    string(7) "ID_KALK"
  }
  ["id"]=>
  int(39644)
}
```

at https://github.com/keboola/db-extractor-mssql/blob/master/src/Keboola/DbExtractor/Extractor/MSSQL.php#L70

**Comment by pivnicek** [comment]
OMG!
